@startuml
!include ../C4_Context.puml

title Диаграмма контекста монолитной системы (AS-IS)

Person(user, "Пользователь", "пользователь приложения")
System(warmhose, "Умный дом ", "приложение для управления отоплением")
System_Ext(api, "Система отопления", "датчики отопления")

Rel(user, warmhose, "Отправляет команды на управление отоплением и получает данные о текущей температуре")
Rel(warmhose, api, "Получает и устанавливает температуру")

@enduml
