@startuml C4_Context_tobe
!include ../C4_Context.puml

title Диаграмма ToBe
Person(user, "Пользователь", "Управляет домом через веб или мобильное приложение")

System(system, "Тёплый дом", "Экосистема для управления умными устройствами и получения телеметрии")

System_Ext(device, "Умное устройство", "Датчики, реле, камеры и др. устройства, подключённые к интернету")
System_Ext(partner, "Партнёрские устройства", "Интеграция через внешние API")

Rel(user, system, "Использует")
Rel(system, device, "Обменивается данными")
Rel(system, partner, "Интегрируется по стандартным протоколам")

@enduml
